name: gms_somatic
channels:
  - bioconda
dependencies:
  - python=3.8
  - fastp=0.20.1
  - bwa=0.7.17
  - samtools=1.9
  - bamtools=2.5.1
  - gatk4=4.1.9.0
  - snakemake-wrapper-utils=0.1.3
  - bcftools=1.9
